import type { User } from '#/entity';

/**
 * 用户弹窗操作类型。
 * 一个弹窗承载新增和编辑流程，使用稳定联合类型避免散落的字符串字面量。
 *
 * User modal action type.
 * One modal handles both create and edit flows, using a stable union type instead of scattered string literals.
 */
export type UserModalType = 'create' | 'edit';

/**
 * 用户表单值。
 * 用户基础字段直接复用项目级 User，角色在表单中仅保存 ID 列表，避免把完整角色对象作为可编辑状态。
 *
 * User form values.
 * Base user fields reuse the project-level User, while the form stores only role ids to avoid editing full role objects in local state.
 */
export type UserFormValues = Omit<Pick<User, 'username' | 'email' | 'status'>, 'id' | 'email'> & {
  /**
   * 用户 ID。
   * 创建时由服务端生成；编辑时携带已有 ID 以标识目标用户。
   *
   * User ID.
   * It is generated by the server during creation and identifies the target user during editing.
   */
  id?: User['id'];

  /**
   * 用户头像。
   *
   * User avatar.
   */
  avatar?: User['avatar'];

  /**
   * 用户邮箱。
   * 项目级 User 允许手机号等其他认证方式，因此邮箱可选；系统用户管理表单要求邮箱，故在此收紧。
   *
   * User email.
   * The project-level User allows other authentication methods such as phone numbers, so email is optional there; the system user form requires it and narrows it here.
   */
  email: string;

  /**
   * 当前选择的角色 ID 列表。
   * 提交时由页面或接口层转换为 User.roles，保持表单状态轻量且与项目实体一致。
   *
   * Selected role ids.
   * The page or API layer converts them to User.roles on submission, keeping form state lightweight and aligned with the project entity.
   */
  roleIds: string[];

  /**
   * 新增或重置时输入的密码。
   * 编辑时留空表示服务端保留原密码，前端不会回填或展示密码。
   *
   * Password entered during creation or reset.
   * An empty value during editing preserves the current password on the server; passwords are never backfilled or displayed in the client.
   */
  password: string;
};

/**
 * 保存用户时提交的数据。
 * 当前与表单值一致；保留独立别名便于未来按接口契约调整载荷而不影响表单状态。
 *
 * Submitted data when saving a user.
 * It currently matches the form values; the separate alias allows future API payload changes without affecting form state.
 */
export type SaveUserPayload = UserFormValues;
